---
- name: Configure EC2 instance to run LAMP stack
  hosts: cit496 
  vars:
    mysql_root_pw: rootpassword

  tasks:
    - name: update repo
      become: true
      apt:
        update_cache: yes

    - name: install git
      become: true
      apt:
        name: git
        state: present
    
    - name: git clone project
      git:
        repo: 'https://github.com/LuongMonica/project4.git'
        clone: yes
        dest: /home/ubuntu/project4
     
    - name: install apache
      become: true
      apt:
        name: apache2
        state: present

    - name: install mysql
      become: true
      apt:
        name: ['mysql-server', 'python-mysqldb']
        state: present

    - name: install pip
      become: true
      apt:
        name: python3-pip 
        state: present

    - name: install pymysql (needed for mysql_user module)
      become: true
      pip:
        name: pymysql
        state: present

    - name: set the mysql root password
      become: true
      community.mysql.mysql_user: 
        name: root 
        password: "{{ mysql_root_pw }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"

    - name: copy .my.cnf with mysql credentials 
      become: true
      template:
        src: templates/my.cnf
        dest: /root/.my.cnf
        mode: 0600

    - name: delete anonymous mysql users for localhost
      become: true
      community.mysql.mysql_user: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: ''
        state: absent
    
    - name: secure mysql root user for ipv4 localhost
      become: true
      community.mysql.mysql_user: name="root" password="{{ mysql_root_pw }}" host="127.0.0.1" login_unix_socket=/var/run/mysqld/mysqld.sock
    
    - name: secure mysql root user for localhost
      become: true
      community.mysql.mysql_user: name="root" password="{{ mysql_root_pw }}" host="localhost" login_unix_socket=/var/run/mysqld/mysqld.sock 
   
    - name: remove the mysql test database
      become: true
      community.mysql.mysql_db: db=test state=absent login_unix_socket=/var/run/mysqld/mysqld.sock

    - name: install debconf & debconf-utils to preconfigure phpmyadmin because it asks questions during installation
      become: true
      apt:
        name: ['debconf', 'debconf-utils']
        state: present
          
    - name: debconf for phpmyadmin
      become: true
      debconf:  name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='apache2' vtype='multiselect'
    
    - name: debconf for phpmyadmin set dbconfig-install
      become: true
      debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'
                    
    - name: debconf for phpmyadmin mysql application password
      become: true
      debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='' vtype='password'
       
    - name: install phpmyadmin
      become: true
      apt:
        name: phpmyadmin
      notify: restart apache

    - name: install php-mbstring
      become: true
      apt:
        name: php-mbstring
        state: present

    - name: create user 'pma' with all privileges
      become: true 
      community.mysql.mysql_user: 
        name: pma
        password: f00barbin
        host: localhost
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      notify: restart mysql

    - name: import mysql table
      community.mysql.mysql_db:
        state: dump
        name: all
        target: /home/ubuntu/project4/idtable.sql

    - name: copy php file to doc root
      become: true
      file:
        src: /home/ubuntu/project4/newid.php
        dest: /var/www/html
  
  handlers:
  - name: restart apache
    become: true
    service:
      name: apache2
      state: restarted

  - name: restart mysql
    become: true
    service:
      name: mysql
      state: restarted
...
