---
- name: Create ec2 instance
  hosts: localhost
  
  tasks: 
  - name: Create key pair
    amazon.aws.ec2_key:
      name: cit496
      key_material: "{{ lookup('file', '/home/mluong/.ssh/id_rsa.pub') }}"

  - name: Create instance
    amazon.aws.ec2:
      key_name: cit496
      instance_tags:
        name: cit496
      instance_type: t2.micro
      # ubuntu 18.04
      image: ami-013f17f36f8b1fefb
      # wait for the instance to start up before returning
      wait: yes
      # the default vpc subnet for us-east-1a
      vpc_subnet_id: subnet-94e181cb
      assign_public_ip: yes
      # security group that i created before in previous proj
      group_id: sg-0161afcc2b60fe968
      volumes:
        - device_name: /dev/sda1
          volume_size: 8
          delete_on_termination: true
...
