---
- name: Terminate EC2
  hosts: localhost

  tasks:
    - name: Terminate it
      amazon.aws.ec2:
        instance_ids: "{{ item.ec2_id }}"
        state: absent
      with_items: "{{ _meta.hostvars }}"
